### ISSUE TITLE
Find a work-around for scanned pdf

### ISSUE THREAD

**Issue by mvicenzi** [mvicenzi/pdf_tools#2]
Scanned pdf documents are not read properly and operations fail.
Investigate this issue: is it a PyPDF2 limitation? is there a workaround?

Possible starting points:
- [https://stackoverflow.com/questions/49939085/xref-table-not-zero-indexed-id-numbers-for-objects-will-be-corrected-wont-con](https://stackoverflow.com/questions/49939085/xref-table-not-zero-indexed-id-numbers-for-objects-will-be-corrected-wont-con)
- [https://github.com/py-pdf/PyPDF2/issues/611](https://github.com/py-pdf/PyPDF2/issues/611)

**Comment by pubpub-zz** [comment]
@mvicenzi, can you provide some pdf samples and a test code for analysis

**Comment by mvicenzi** [comment]
@pubpub-zz you can find the simplest code to reproduce the error [here](https://github.com/mvicenzi/pdf_tools/blob/2-find-a-work-around-for-scanned-pdf/debugging_scanned.py). The sample pdf file is [this one](https://github.com/mvicenzi/pdf_tools/blob/2-find-a-work-around-for-scanned-pdf/test/test_scanned.pdf), which was generated with a scanner.

**Comment by pubpub-zz** [comment]
I've tried with the dev version without any error.can you retry with the latest version of PyPDF2?

**Comment by mvicenzi** [comment]
I upgraded PyPDF2 from 1.27.3 to 1.27.12, but I still see errors.
I'm on python 3.10.2

```PdfReadWarning: Xref table not zero-indexed. ID numbers for objects will be corrected. [_reader.py:1065]
Traceback (most recent call last):
  File "C:\Users\matte\Desktop\pdf_tools\debugging_scanned.py", line 7, in <module>
    merger.append(path1, bookmark=None, pages=None, import_bookmarks=True)
  File "C:\Users\matte\AppData\Local\Programs\Python\Python310\lib\site-packages\PyPDF2\merger.py", line 227, in append
    self.merge(len(self.pages), fileobj, bookmark, pages, import_bookmarks)
  File "C:\Users\matte\AppData\Local\Programs\Python\Python310\lib\site-packages\PyPDF2\merger.py", line 157, in merge
    pages = (0, pdfr.getNumPages())
  File "C:\Users\matte\AppData\Local\Programs\Python\Python310\lib\site-packages\PyPDF2\_reader.py", line 318, in getNumPages
    self._flatten()
  File "C:\Users\matte\AppData\Local\Programs\Python\Python310\lib\site-packages\PyPDF2\_reader.py", line 706, in _flatten
    catalog = self.trailer[TK.ROOT].getObject()
  File "C:\Users\matte\AppData\Local\Programs\Python\Python310\lib\site-packages\PyPDF2\generic.py", line 553, in __getitem__
    return dict.__getitem__(self, key).getObject()
  File "C:\Users\matte\AppData\Local\Programs\Python\Python310\lib\site-packages\PyPDF2\generic.py", line 198, in getObject
    return self.pdf.getObject(self).getObject()
  File "C:\Users\matte\AppData\Local\Programs\Python\Python310\lib\site-packages\PyPDF2\_reader.py", line 801, in getObject
    raise PdfReadError(
PyPDF2.errors.PdfReadError: Expected object ID (8 0) does not match actual (7 0); xref table not zero-indexed.
```

I also tried cloning again the repo to check if uploading the pdf had fixed the file somehow, but no.... Still the same error as above.

**Comment by pubpub-zz** [comment]
I've understood : your PDF does not respect the rule where the xref table should start at 0, inducing a PdfReadError if strict is asserted. PyPDF2 moved to strict = False as default, but PdfFileMerger has been forgotten. I will push the fix however meanwhile you can initialize with strict = False:

`merger = PdfFileMerger( strict = False)`
